Fix dev-env api container setup
The installation of the python packages in the dev-env api container
failed with this error:

```
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /solidago
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
WARNING: You are using pip version 21.2.4; however, version 23.3.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
```

It looks like using pyproject.toml requires a newer version of
setuptools. Upgrading to a newer Debian worked.